#include <stdio.h>
#include "hocdec.h"
extern int nrnmpi_myid;
extern int nrn_nobanner_;

extern void _5ht_reg(void);
extern void _CaL_reg(void);
extern void _DNav18_reg(void);
extern void _Ka_reg(void);
extern void _Kv_reg(void);
extern void _NaF_reg(void);
extern void _NaP_reg(void);
extern void _Nav17_a_reg(void);
extern void _Nav18_a_reg(void);
extern void _aabBK_reg(void);
extern void _atp3_reg(void);
extern void _atp4_reg(void);
extern void _atp42_reg(void);
extern void _bk_reg(void);
extern void _cat_reg(void);
extern void _extrapump_reg(void);
extern void _kDR_reg(void);
extern void _k_ion_dynamics_reg(void);
extern void _kadist_reg(void);
extern void _kaprox_reg(void);
extern void _kdr0_reg(void);
extern void _kdr2_reg(void);
extern void _kf_reg(void);
extern void _ks_reg(void);
extern void _leak_reg(void);
extern void _na_reg(void);
extern void _na_ion_dynamics_reg(void);
extern void _nafast_reg(void);
extern void _nakpump_reg(void);
extern void _naslow_reg(void);
extern void _nattxs_reg(void);
extern void _nav18_reg(void);
extern void _nav1p8_reg(void);
extern void _p2x2_reg(void);
extern void _p2x3_reg(void);
extern void _sk_reg(void);

void modl_reg(){
  if (!nrn_nobanner_) if (nrnmpi_myid < 1) {
    fprintf(stderr, "Additional mechanisms from files\n");

    fprintf(stderr," ./mod/5ht.mod");
    fprintf(stderr," ./mod/CaL.mod");
    fprintf(stderr," ./mod/DNav18.mod");
    fprintf(stderr," ./mod/Ka.mod");
    fprintf(stderr," ./mod/Kv.mod");
    fprintf(stderr," ./mod/NaF.mod");
    fprintf(stderr," ./mod/NaP.mod");
    fprintf(stderr," ./mod/Nav17_a.mod");
    fprintf(stderr," ./mod/Nav18_a.mod");
    fprintf(stderr," ./mod/aabBK.mod");
    fprintf(stderr," ./mod/atp3.mod");
    fprintf(stderr," ./mod/atp4.mod");
    fprintf(stderr," ./mod/atp42.mod");
    fprintf(stderr," ./mod/bk.mod");
    fprintf(stderr," ./mod/cat.mod");
    fprintf(stderr," ./mod/extrapump.mod");
    fprintf(stderr," ./mod/kDR.mod");
    fprintf(stderr," ./mod/k_ion_dynamics.mod");
    fprintf(stderr," ./mod/kadist.mod");
    fprintf(stderr," ./mod/kaprox.mod");
    fprintf(stderr," ./mod/kdr0.mod");
    fprintf(stderr," ./mod/kdr2.mod");
    fprintf(stderr," ./mod/kf.mod");
    fprintf(stderr," ./mod/ks.mod");
    fprintf(stderr," ./mod/leak.mod");
    fprintf(stderr," ./mod/na.mod");
    fprintf(stderr," ./mod/na_ion_dynamics.mod");
    fprintf(stderr," ./mod/nafast.mod");
    fprintf(stderr," ./mod/nakpump.mod");
    fprintf(stderr," ./mod/naslow.mod");
    fprintf(stderr," ./mod/nattxs.mod");
    fprintf(stderr," ./mod/nav18.mod");
    fprintf(stderr," ./mod/nav1p8.mod");
    fprintf(stderr," ./mod/p2x2.mod");
    fprintf(stderr," ./mod/p2x3.mod");
    fprintf(stderr," ./mod/sk.mod");
    fprintf(stderr, "\n");
  }
  _5ht_reg();
  _CaL_reg();
  _DNav18_reg();
  _Ka_reg();
  _Kv_reg();
  _NaF_reg();
  _NaP_reg();
  _Nav17_a_reg();
  _Nav18_a_reg();
  _aabBK_reg();
  _atp3_reg();
  _atp4_reg();
  _atp42_reg();
  _bk_reg();
  _cat_reg();
  _extrapump_reg();
  _kDR_reg();
  _k_ion_dynamics_reg();
  _kadist_reg();
  _kaprox_reg();
  _kdr0_reg();
  _kdr2_reg();
  _kf_reg();
  _ks_reg();
  _leak_reg();
  _na_reg();
  _na_ion_dynamics_reg();
  _nafast_reg();
  _nakpump_reg();
  _naslow_reg();
  _nattxs_reg();
  _nav18_reg();
  _nav1p8_reg();
  _p2x2_reg();
  _p2x3_reg();
  _sk_reg();
}
